language: dart
notifications:
  slack: equinox-initiative:cDBwKqSOwzDkyhAyHQgriUvF
    on_pull_requests: false
    on_success: always
    on_failure: always
    on_cancel: always
    on_error: always
    on_start: always